server:
  port: 12001

spring:
  application:
    name: user-service
eureka:
  instance:
    hostname: eureka
  client:
    eureka-connection-idle-timeout-seconds: 10
    instance-info-replication-interval-seconds: 10
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:2901/eureka/,http://${eureka.instance.hostname}:2902/eureka/
